import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Import czcionki
import "./globals.css";

// Konfiguracja czcionki
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Moja Duża Aplikacja",
  description: "Generated by Gemini Next.js stack",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      {/* Aplikowanie czcionki do całego body */}
      <body className={inter.className}>{children}</body>
    </html>
  );
}